[package]
name = "plane-proj"
description = "Zero-dependency fact approximate distance on Earth calculation"
version = "0.1.0"
repository = "https://github.com/kinkard/plane-proj"
readme = "README.md"
include = ["**/*.rs"]
keywords = ["geo", "maps"]
edition = "2021"
authors = ["Stepan Kizim <stsiapan.kizim@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
# No dependencies
